services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    command: sh -c "python src/db/migrate.py && 
                    uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend/
    command: sh -c "npm start"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/
    restart: on-failure

volumes:
  data: